server:
  port: 80
  servlet:
    context-path: /spider

spring:
  datasource:
    url:  jdbc:mysql://192.168.47.128:3306/spider_demo_prod?allowMultiQueries=true
    username: root
    password: 123456

  redis:
    host: 140.143.168.15
    password:
    port: 6379
    database: 7
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
