server:
  port: 8080
  servlet:
    context-path: /spider

spring:
  datasource:
    url:  jdbc:mysql://192.168.47.128:3306/spider_demo?allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 140.143.168.15
    password:
    port: 6379
    database: 5
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1